### ISSUE TITLE
auto fill

### ISSUE THREAD

**Issue by shaggy2dabs** [carl1to/Cop-It-Supreme-Bot#10]
your auto fill codes are wrong for the credit card and cvc number 5 min before the drop supreme changes it i have the codes i dont know much about this stuff but i used another auto filler program that has diff codes then yours the ones u have now work now but at the drop they dont  

these are the regular that work onsite now 
$('#cnb').val(r.card_number)
$('#vval').val(r.cvv)

these are the ones that work at the drop 
$('#nlb').val(r.card_number)
$('#rvv').val(r.cvv)

**Comment by albertogasparin** [comment]
On the UK checkout `#cnb` and `#vval` are still the correct ones

**Comment by shaggy2dabs** [comment]
is there n e way to make it do both cause the us site changes it at the drop ?

**Comment by adrichman** [comment]
I have created a pull request for these changes here: https://github.com/carl1to/Cop-It-Supreme-Bot/pull/13

**Comment by AceroM** [comment]
Just Incase supreme changes it again I changed it to this jquery selector code
so that it doesn't matter if they change the name or id tag of the specific values.
```js
$("#card_details > div > input").eq(0).val(r.card_number)
$("#card_details > div > input").eq(1).val(r.cvv)
$("#card_details > div > select").eq(0).val(r.card_month);
$("#card_details > div > select").eq(1).val(r.card_year);
```

**Comment by shaggy2dabs** [comment]
man i wish i knew what all these terms meant lmao im a super noob but the codes i posted came from the add on AUTOFILL  the first one is after i reset it durring the drop and the other one is before the drop you see how it the two extra lines at the bottom it wont matter if i use your updates?
![auto fill drop 2](https://user-images.githubusercontent.com/29291907/30253109-876922ee-964c-11e7-8252-76c12b3b22cb.jpg)
![auto fill](https://user-images.githubusercontent.com/29291907/30253115-9b1fe692-964c-11e7-9926-a6b170fc8d50.jpg)

**Comment by adrichman** [comment]
@AceroM love this! I'm going to amend my pull request with those changes

**Comment by adrichman** [comment]
@shaggy2dabs it sounds like you're not using the extension to fill out the form. those new options look like they might work but who knows come drop day

**Comment by shaggy2dabs** [comment]
@adrichman I'm not using the extension to fill out the form I'm using the auto fill extension on top of it and it feels it out just fine if I don't have it running at the same time it will not fill out the credit card and CVC I'm 1 million percent positive that the two extra codes on the bottom work for the u.s. drop because I have given them to my friends who have manually added them to their autofill extension and it works for them cuz they had the same problem with the credit card and CVC not filling out with the original codes that the autofilter gave them when they set up the autofill not during the drop does that make sense?

**Comment by adrichman** [comment]
@shaggy2dabs makes sense, except for your certainty. I know these fields are working now, and I also tested them. On the day of the drop they may be changed, though. We can't possibly know for sure.
