### ISSUE TITLE
USA Add to cart currently not working

### ISSUE THREAD

**Issue by thmshwkns** [carl1to/Cop-It-Supreme-Bot#12]
With correct keywords + colours the bot does not manage to find items and add them to cart. Still working on UK however.

**Comment by AceroM** [comment]
I changed 
```js
var articles = document.getElementsByTagName("article");
```
to
```js
var articles = document.getElementsByClassName("item");
```
and it worked. I think supreme removed the tag name article on the website for US. I am unsure

**Comment by thmshwkns** [comment]
Where did you change it? Sorry I'm new to coding

**Comment by thmshwkns** [comment]
Any chance you could describe how I change that code and then recompile the extension?

**Comment by AceroM** [comment]
just change the code and then type 
gulp install
in a directory using the command line

**Comment by adrichman** [comment]
I have created a pull request for these changes here: https://github.com/carl1to/Cop-It-Supreme-Bot/pull/13

**Comment by carl1to** [comment]
I'll be back at the end of the month. I will fix all issues and add new features.

**Comment by superman2004** [comment]
i dont understand how to do any of the coding stuff or modifications to the bot
would anyone mind helping me out or sending screenshots or something?
