### ISSUE TITLE
CVV doesn't work anymore

### ISSUE THREAD

**Issue by gerry02** [carl1to/Cop-It-Supreme-Bot#22]
can you fix the code? becouse the Supreme site has been updated and the CVV code of the "Cop It Bot" doesn't work anymore.
Thanks.

**Comment by AceroM** [comment]
should be fixed with 
```js
$("#vval").val(r.cvv);
```
idk if supreme will change the id of the cvv in the last second so this could just be a tentative fix...
I'll check out the website after the drop happens and look for any changes.

**Comment by gerry02** [comment]
Thank you bro💪🏼

**Comment by robbymurphy** [comment]
@AceroM you can always use a different selector like `$('input[placeholder="CVV"]')` instead.  that will work no matter what the id is.

**Comment by gerry02** [comment]
the fix doesn't work for me! :(

**Comment by gerry02** [comment]
someone says how to fix the code??

**Comment by AceroM** [comment]
@robbymurphy 
good selector thanks

**Comment by gerry02** [comment]
@AceroM I fix the code with your code but i had to write "CVV" in lowercase
