### ISSUE TITLE
It won't let me add CopIt.crx to Chrome

### ISSUE THREAD

**Issue by hsolish** [carl1to/Cop-It-Supreme-Bot#3]
I used to just drag and drop the file, but for some reason it won't let me anymore. How else can I add the CopIt file to the chrome extensions? Thanks.

**Comment by kmccmk9** [comment]
I'm having no issue with drag and drop in Version 60.0.3112.90 (Official Build) (64-bit)

Check and make sure you also have enabled Developer Mode

**Comment by PlayboyIsaac** [comment]
I got it up and running, if you need any kind of help I will gladly do so! Email me at Isaacramseycox@gmail.com

**Comment by hsolish** [comment]
It just started working, I don't know what I was doing wrong! I have one
quick question- everytime I shut down chrome, it makes me re-install the
extension since it is not in the app store. Is there a way to stop this?
Thanks.

**Comment by PlayboyIsaac** [comment]
Honestly, I don't think so. I tried to find out a solution to stop it from doing so and all the forums say it's basically impossible. You can install Chromium, but that's not worth it in my opinion. I'll personally pay the $5 just to upload it to the Chrome Store.

**Comment by hsolish** [comment]
Ah oh gotcha. And yeah, I would gladly split those fees with you! I will
definenlty support this project. Have you copped anything big with the bot?
I got a Michael Jackson tee with it last season and hopefully get some big
stuff this upcoming season!

**Comment by carl1to** [comment]
Sorry for delay.

If it doesn't work on Google Chrome then try Chromium.
