### ISSUE TITLE
Committed node_modules

### ISSUE THREAD

**Issue by jgouly** [carl1to/Cop-It-Supreme-Bot#5]
Did you mean to commit all the node_modules folder?

**Comment by carl1to** [comment]
Just clone the repository, go into with your terminal and type `npm install` 

And you will have the node_modules folder

**Comment by jgouly** [comment]
https://github.com/carl1to/Cop-It-Supreme-Bot/commit/a364980b2161c9ace32cabdb7d1aec2ed4047df7
Showing 6,811 changed files with 442,775 additions and 4 deletions.

Did you mean to commit your node_modules folder?
