### ISSUE TITLE
Key Words Error

### ISSUE THREAD

**Issue by nochace549** [carl1to/Cop-It-Supreme-Bot#6]
I was trying out the bots keyword tool for the first time just on some unsold items on the current drop. Therefore keywords are an exact match (I tried this with multiple different items), but when I hit start on the bot it only takes me to the category page and thus I get the error without the bot adding anything to cart. I hope the screenshot helps to provide context.
<img width="1275" alt="screen shot 2017-08-24 at 11 42 16 pm" src="https://user-images.githubusercontent.com/31337104/29702489-62fb8ae2-8926-11e7-8de5-2bc357687c75.png">

**Comment by carl1to** [comment]
The problem has been fixed.

I just forgot a `.toLowerCase()`. Now it will works perfectly (you should had to put the colour in lowercase but now there is no longer importance).
