### ISSUE TITLE
Key Words Auto Cart Error

### ISSUE THREAD

**Issue by nochace549** [carl1to/Cop-It-Supreme-Bot#7]
Honestly, I commend you for fixing my issue so quickly yesterday, but now I am at a new standstill where the keywords actually find the product now, but they don't get added to cart only goes to the items page. Hope this helps.
![ezgif com-optimize](https://user-images.githubusercontent.com/31337104/29732765-f20a5984-899e-11e7-8753-dc34d7fba696.gif)

**Comment by carl1to** [comment]
Okay please try to clear all your supreme's cookies.

If it doesn't work anymore, let me know I'll check.

This works nice for me because I'm on UK Web Store, US is probably different...

**Comment by carl1to** [comment]
I just checked and indeed there is an error, I fixed it.
