### ISSUE TITLE
Province

### ISSUE THREAD

**Issue by soleHats** [carl1to/Cop-It-Supreme-Bot#9]
Hi there tnx for this awesome chrome extension this is Lit but there is just a little problem from auto fill cuz if u choose country to CANADA the province does not select a province when u checkout thats why if u someone using auto checkout they will fail cuz u need to choose a province manually!

**Comment by jserafin** [comment]
Looked into this issue a bit more. It looks like the selected attribute for the country is not being updated - while the drop down value is changed to CANADA, selected="selected" remains on USA.
